# Hugo-defined variables
baseURL = "https://openinternals.github.io/"
languageCode = "en-us"
title = "The Open Internals Podcast"
theme = "hugo-theme-cactus-plus"

# Enable Emoji emoticons support for page content; see emoji-cheat-sheet.com
enableEmoji = true

# google analytics
googleAnalytics = "UA-58520192-2"

# the length of text to show in a .Summary
summaryLength = 70

# Pagination (3,6,9,12, ...)
paginate =  6

# Syntax Highlighting
pygmentscodefences            = true
pygmentsUseClasses            = true

[params]
author = "darshanime"
enableTwitterCard = true

enableDisqus = true
disqusShortname = "openinternals"

bio = "Podcast about the internals of popular open source packages"
enableRSS = true